# Generated by Django 3.0.4 on 2020-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtpSysInfo',
            fields=[
                ('system_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=128)),
                ('system_abbr', models.CharField(max_length=64, null=True)),
                ('system_type', models.CharField(max_length=32, null=True)),
                ('ascription', models.CharField(max_length=32, null=True)),
                ('online_time', models.CharField(max_length=10, null=True)),
                ('url_address', models.CharField(max_length=128, null=True)),
                ('account', models.CharField(max_length=64, null=True)),
                ('admin_address', models.CharField(max_length=128, null=True)),
                ('admin_account', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
