# Generated by Django 3.0.4 on 2020-03-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtpSysInfo',
            new_name='Info',
        ),
    ]
