# Generated by Django 3.0.4 on 2020-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20200321_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='online_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
