# Generated by Django 3.0.4 on 2020-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20200322_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='online_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
